variables:
- group: AzureDemo

trigger:
  branches:
    include:
      - main

pool:
  vmImage: 'ubuntu-latest'

stages:
  - stage: BuildAndDeploy
    displayName: 'Build And Deployment Stage'
    jobs:
      - job: Build
        displayName: 'Build Job'
        steps:

          - task: NodeTool@0
            inputs:
              versionSpec: '19.x'
            displayName: 'Install Node.js'

          - script: |
              echo 'Installing dependencies...'
              npm install
            displayName: 'Install Dependencies'

          - script: |
              echo 'Building application...'
              npm run build --verbose
            displayName: 'Build'


      - job: Test
        dependsOn: Build
        displayName: 'Test Job'
        steps:

          - task: NodeTool@0
            inputs:
              versionSpec: '19.x'
            displayName: 'Install Node.js'

          - script: |
              echo 'Installing dependencies...'
              npm install
            displayName: 'Install Dependencies'

          - script: |
              echo 'Building application...'
              npm run build --verbose
            displayName: 'Build'

          - script: |
              echo 'Running unit tests...'
              CI=true npm test
            displayName: 'Running Unit Tests'


      - job: Deploy
        dependsOn: Test
        displayName: 'Deployment Job'
        steps:

          - task: NodeTool@0
            inputs:
              versionSpec: '19.x'
            displayName: 'Install Node.js'

          - script: |
              echo 'Installing Nelify CLI...'
              npm i netlify-cli -g
            displayName: 'Install Netlify CLI'

          - script: |
              echo 'Installing dependencies...'
              npm install
            displayName: 'Install Dependencies'

          - script: |
              echo 'Building application...'
              npm run build --verbose
            displayName: 'Build'

          - script: |
              echo 'Deploying to Netlify...'
              netlify deploy "--auth=$(netlifyApiKey)" "--site=$(netlifySiteKey)" "--dir=$(Agent.WorkFolder)/1/s/build" --prod --verbose
            displayName: 'Deploy to Netlify'
