trigger:
  branches:
    include:
      - main

pool:
  vmImage: 'ubuntu-latest'

steps:
  - task: NodeTool@0
    inputs:
      versionSpec: '12.x'
    displayName: 'Install Node.js'

  - script: |
      echo 'Installing dependencies...'
      npm ci
    displayName: 'Install Dependencies'

  - script: |
      echo 'Building application...'
      npm run build
    displayName: 'Build'

  - script: |
      echo 'Running unit tests...'
      npm run test
    displayName: 'Unit Tests'

  - task: PublishPipelineArtifact@1
    inputs:
      targetPath: '$(Build.ArtifactStagingDirectory)'
      artifact: 'app'
      publishLocation: 'pipeline'
    displayName: 'Publish Artifact'

