# File: azure-demo.yml

trigger:
  branches:
    include:
      - main

pool:
  vmImage: 'ubuntu-latest'

stages:
  - stage: Build
    displayName: 'Build Stage'
    jobs:
      - job: Build
        displayName: 'Build Job'
        steps:
          - script: |
              echo 'Performing build tasks...'
              # Add your build commands here
              # For example:
              # npm install
              # npm run build
            displayName: 'Build'

  - stage: Test
    displayName: 'Test Stage'
    dependsOn: Build
    jobs:
      - job: UnitTests
        displayName: 'Run Unit Tests'
        steps:
          - script: |
              echo 'Running unit tests...'
              # Add your unit test commands here
              # For example:
              # npm run test
            displayName: 'Unit Tests'

      - job: IntegrationTests
        displayName: 'Run Integration Tests'
        steps:
          - script: |
              echo 'Running integration tests...'
              # Add your integration test commands here
            displayName: 'Integration Tests'

  - stage: Deploy
    displayName: 'Deployment Stage'
    dependsOn: Test
    jobs:
      - deployment: DeployWebApp
        displayName: 'Deploy to Web App'
        environment: 'production'
        strategy:
          runOnce:
            deploy:
              steps:
                - script: |
                    echo 'Deploying to web app...'
                    # Add your deployment commands here
                    # For example:
                    # az webapp deploy
                  displayName: 'Deploy to Web App'
